# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AddField(
            model_name='status',
            name='batch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Batch'),
            preserve_default=False,
        ),
    ]
